// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVpP-aasdZDzxGBOjHlc9DGzRd5V0hDYo',
    appId: '1:273077207210:web:1bdf48688e4e80ba40d0d3',
    messagingSenderId: '273077207210',
    projectId: 'apple-clone-alarm-project',
    authDomain: 'apple-clone-alarm-project.firebaseapp.com',
    storageBucket: 'apple-clone-alarm-project.firebasestorage.app',
    measurementId: 'G-FMSZQ3BSPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaNwySjW-CoLCkLums-W226Ql9PqxBLdc',
    appId: '1:273077207210:android:afb92105bbf518fa40d0d3',
    messagingSenderId: '273077207210',
    projectId: 'apple-clone-alarm-project',
    storageBucket: 'apple-clone-alarm-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsLe96vasZFN50Stx6cgoBg2UJSqwEFh4',
    appId: '1:273077207210:ios:8624b41f445ff89d40d0d3',
    messagingSenderId: '273077207210',
    projectId: 'apple-clone-alarm-project',
    storageBucket: 'apple-clone-alarm-project.firebasestorage.app',
    iosBundleId: 'com.example.appleCloneAlarmProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsLe96vasZFN50Stx6cgoBg2UJSqwEFh4',
    appId: '1:273077207210:ios:8624b41f445ff89d40d0d3',
    messagingSenderId: '273077207210',
    projectId: 'apple-clone-alarm-project',
    storageBucket: 'apple-clone-alarm-project.firebasestorage.app',
    iosBundleId: 'com.example.appleCloneAlarmProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVpP-aasdZDzxGBOjHlc9DGzRd5V0hDYo',
    appId: '1:273077207210:web:fc7c69bf3c1d3b7e40d0d3',
    messagingSenderId: '273077207210',
    projectId: 'apple-clone-alarm-project',
    authDomain: 'apple-clone-alarm-project.firebaseapp.com',
    storageBucket: 'apple-clone-alarm-project.firebasestorage.app',
    measurementId: 'G-FHQLKQVLKL',
  );
}
